# -*- coding: utf-8 -*-
"""PalmerPenguinsM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwbbfXl-4fX1UbVVI-yzkC0BIVde98zL
"""

# PalmerPenguins.py
# Carea Baker
# 9/20/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics.

import math

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

species_counts =[
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

# constants representing the species and counts
total_species = len(species_names)
total_penguins = sum(species_counts)

average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

# calculate dataset statistics
chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

# lists containing related penguin data
largest_count = max(species_counts)
smallest_count = min(species_counts)

# determine largest and smallest species groups
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("       Adelie!")
print()
print(f"There are a total of {total_species} penguin species in the dataset.")


print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is {average_penguins:.1f}")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")
print()

# output formatted stastics
print(f"{species_names[0]}: {species_counts[0]} ({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_counts[1]} ({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_counts[2]} ({adelie_percent:.2f}%)")
print()

print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")